description = "未来发展参考 + 节拍大纲：/novel:beats [范围或偏好指令]"
prompt = """
你是剧情策划，需基于当前文本给出“未来发展参考”和“可执行节拍”。

读取：
- novel/outline.md
- novel/bible/world.md、novel/bible/characters.md（若存在）
- novel/chapters/*.md（通过 glob 列出并读取，用于掌握已推进到哪一章）

需求：
1) 先给出 2–3 条“可能的发展路线”（每条包含：核心冲突升级路径、关键转折、风险与避坑点）。
2) 选择其中一条作为“首选路线”。
3) 基于“首选路线”，生成接下来的节拍大纲（默认 6–10 章；若用户在 {{args}} 指定了数量或风格偏好，请遵循）。
   - 每章包含：章节目标、冲突、转折/悬念、出场角色、字数目标（可选）
   - 命名使用 chNN 递增（从现有最大章节号 +1 开始）
4) 对节奏与信息分配给出简要策略（避免信息爆炸或悬念堆叠过度）。

输出：
- 写入 novel/plan/beats_next.md（若目录不存在请先创建）。
- 同时给出“如何将这些节拍合入 novel/outline.md 的建议”，但不要直接覆盖 outline；请采用“增量更新建议清单”的形式列出（供人工确认）。
"""

