description = "生成或扩写指定章节：/novel:chapter <chNN> [补充指令]"
prompt = """
根据大纲与人物设定，为 {{args}} 生成或扩写章节草稿。

步骤：
1) 读取 novel/outline.md、novel/bible/characters.md、novel/bible/world.md；
2) 若存在对应文件 novel/chapters/{{args}}.md：
   - 先在同目录创建备份文件 novel/chapters/{{args}}_rev1.md（若 _rev1 已存在则递增编号 _rev2、_rev3…）。
3) 生成本章：
   - 章节目标；
   - 场景表（表格/清单：场景序号、POV、场景目标、冲突、转折、出场角色、伏笔/呼应）；
   - 正文草稿（语言流畅、具画面感，避免堆砌抽象词）。
4) 若 {{args}} 后面附带了补充指令（例如“紧张节奏、双 POV、2k 字左右”），需在写作时遵循。

输出：写入 novel/chapters/{{args}}.md（覆盖写回）。
"""

