description = "创建或完善人物卡：/novel:character <角色名>"
prompt = """
请为角色 {{args}} 创建或完善人物卡。

要求：
- 读取 novel/bible/characters.md，若已存在对应二级标题则在该节下“增量完善”；否则新增完整卡片。
- 字段：姓名｜人设标签｜外貌｜背景｜目标｜动机｜冲突｜成长弧线｜关系｜技能与限制｜口头禅/习惯｜重要道具/设定。
- 保持 Markdown 结构规整，使用二级标题“## {{args}}”。

完成后使用 write_file 写回 novel/bible/characters.md（保留其他角色不变）。
"""

