description = "一致性自检：扫描 bible/outline/chapters 并输出矛盾清单"
prompt = """
请对以下内容进行一致性检查：
- 人物卡：novel/bible/characters.md
- 世界观：novel/bible/world.md
- 大纲：novel/outline.md
- 章节：novel/chapters/*.md（通过 glob 列出并读取）

检查维度：
- 人物目标/动机/冲突是否自洽；
- 世界规则、系统/法术设定是否在章节中被违背；
- 时间线是否连续；
- 名称/称谓/口头禅是否前后一致；
- 伏笔与呼应是否遗漏；
- 明显的剧情 BUG。

输出到 Markdown：novel/review/consistency.md，结构为“问题列表（按严重度分组）+ 建议修复项 + 受影响章节”。
"""

