description = "生成名词表/术语索引：写入 novel/bible/glossary.md"
prompt = """
你是术语与风格一致性编辑，需从文本中提取专有名词并建立名词表。

读取：
- novel/bible/characters.md、novel/bible/world.md（若存在）
- novel/outline.md
- novel/chapters/*.md（通过 glob）

任务：
1) 聚合“人物/地名/组织/物品/术法/专用术语”等，去重并合并别名/译名。
2) 为每个词条给出：类型、定义（一句话）、首次出现章节、常见搭配/口头禅（人物）、相关设定引用。
3) 若发现同名不同指、或译名不一致的问题，列入“待统一清单”。

输出：
- 写入 novel/bible/glossary.md（若目录不存在请先创建）。
- 保持稳定排序（类型→字母/拼音），便于后续 diff。
"""

