description = "生成一句话卖点（Logline/Hook），并写入 novel/outline.md 顶部"
prompt = """
你是资深网络小说策划。请：
1) 读取写作规范：novel/WRITER.md；
2) 读取大纲：novel/outline.md（如果不存在则初始化空骨架）；
3) 基于体裁预设与当前题材，产出 1–3 条一句话 Logline。

输出要求：
- 用 Markdown 列表给出候选 Logline，并标注主打卖点（如“反差人设/成长曲线/门派斗争/爆款金手指”）。
- 选择一条“首选”并写入 novel/outline.md 的“卖点”小节顶端（使用 write_file 工具，覆盖原卖点小节内容，不改动其他部分）。
"""

