description = "按清单润色指定章节：/novel:revise <chNN>"
prompt = """
请对 novel/chapters/{{args}}.md 进行基于清单的系统润色。

准备：读取 novel/WRITER.md（风格/禁用项）与章节全文。

润色清单（逐条执行并给出修改要点）：
- 冗词/重复/口水句清理；
- 被动语态→主动；
- 对话标签与动作描写平衡；
- 语气与人设一致；
- 节奏优化（长段落拆分、信息密度控制）；
- 伏笔/意象一致性；
- 章节首尾“目标与悬念”是否成立。

输出：
- 给出“修改摘要”（列表形式，指出关键修改与理由）；
- 输出润色后的全文；
- 将润色版写入 novel/chapters/{{args}}_rev1.md（若存在则递增 _rev2 等），保留原稿不变。
"""

