description = "汇总当前故事与细节：输出总览、角色动态、伏笔与悬念，写入 novel/review/summary.md"
prompt = """
你是故事编辑，负责对现有文本做“信息汇总与状态盘点”。

读取：
- novel/outline.md
- novel/bible/world.md（若存在）
- novel/bible/characters.md（若存在）
- novel/chapters/*.md（通过 glob 列出并读取）

请生成一份结构化总结，包含：
1) 故事总览（主题/冲突/进展/当前所处阶段）
2) 角色动态（主要角色各自的 目标/动机/冲突/新信息/关系变动）
3) 事实与设定清单（从章节文本中抽取关键“可验证事实”；标注首次出现章节与引用处）
4) 伏笔与呼应（已埋伏笔、已呼应、待呼应清单）
5) 未解决悬念（按紧急程度排序）
6) 潜在问题与风险（逻辑、节奏、设定使用上的隐患）
7) 附录：每章三行梗概（chNN：三行以内，客观描述，不剧评）

输出：
- 将报告写入 novel/review/summary.md（若目录不存在请先创建）。
- 清晰的 Markdown 结构，便于后续 diff 与增量维护。
"""

