description = "生成故事时间线与校验点：写入 novel/bible/timeline.md"
prompt = """
你是时间线统筹，请基于现有文本抽取并规范化时间线。

读取：
- novel/outline.md
- novel/chapters/*.md（通过 glob）
- novel/bible/world.md（若存在，用于历法/时序规则）

任务：
1) 抽取“明确时间指示/相对时间/昼夜/节日/年龄/历次事件顺序”等线索，归一化为统一时间线（若存在历法，按该历法；否则以“Day 0 / Week 1”等相对标尺）。
2) 标注每条事件的来源章节与证据句。
3) 标记潜在矛盾（如同日多时地、年龄不一致、旅行时长不合理等），并给出最小代价修正建议。

输出：
- 写入 novel/bible/timeline.md，包含：
  - 时间线（表格或分层列表）
  - 矛盾清单与修正建议
  - 附：抽取规则与假设（便于后续维护）
"""

