description = "生成或更新世界观：novel/bible/world.md"
prompt = """
你是一名资深世界观设定编辑。请基于现有资料，生成或增量更新本项目的世界观文档。

输入资料：
- 写作规范与口吻：novel/WRITER.md
- 大纲：novel/outline.md（若无则忽略相关交叉校验）
- 人物卡：novel/bible/characters.md（若无则忽略）
- 既有世界观文件：novel/bible/world.md（若存在需“保留既有有效内容并增量完善”）

目标：
1) 若 world.md 不存在，创建结构化骨架；若存在，在不删除原有有效信息的前提下进行“结构梳理 + 增量补全”。
2) 保持术语一致，避免与人物/大纲冲突；发现冲突时在“设定冲突清单”中列出并给出建议修正。

推荐文档结构（可按题材微调）：
# 世界观纲要（电梯陈述、类型/母题/基调）
## 世界规则（硬规则/软约束；能力体系：来源/代价/成长/限制）
## 地理与势力（地区、组织、宗教、门派/家族、冲突版图）
## 历史与时间线（关键事件年表）
## 文化与日常（经济/资源、货币、度量衡、交通、饮食、礼仪）
## 技术/法术/系统设定（可与规则互引）
## 术语表（核心名词与定义；与 glossary 对齐）
## 禁用/避免项（与 WRITER.md 保持一致）
## 设定冲突清单（若有）

输出：
- 使用 write_file 将结果写入 novel/bible/world.md；若目录不存在请先创建。
- 对于“增量更新”，请在保持原有小节顺序的前提下：
  - 追加缺失小节；
  - 在现有小节中以小标题或列表形式补充，而非整体覆盖；
  - 保留作者手写段落和注释。
"""

